function h = measurementModelDualState(x,v,F,m,k1,k2,c)
%MEASUREMENTMODELDUALSTATE
%    H = MEASUREMENTMODELDUALSTATE(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Jul-2015 04:00:35

h = [v;F];
