function dw = paramExplicitODEDualState(x,v,F,m,k1,k2,c)
%PARAMEXPLICITODEDUALSTATE
%    DW = PARAMEXPLICITODEDUALSTATE(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Jul-2015 04:00:36

dw = [0.0;0.0;0.0];
