function df_dX = dynamicsDerivatives(x,v,F,m,k1,k2,c)
%DYNAMICSDERIVATIVES
%    DF_DX = DYNAMICSDERIVATIVES(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    30-Jul-2015 17:04:08

t2 = 1.0./m;
df_dX = reshape([0.0,-t2.*(k1+k2.*x.^2.*3.0),0.0,1.0,-c.*t2,0.0,0.0,t2,0.0],[3, 3]);
