function h = measurementModelNonLinear(x,v,m,k1,k2,omega,Amplitude,t)
%MEASUREMENTMODELNONLINEAR
%    H = MEASUREMENTMODELNONLINEAR(X,V,M,K1,K2,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jul-2015 14:27:17

h = v;
