function h = measurementModel(x,v,m,k,omega,Amplitude,t)
%MEASUREMENTMODEL
%    H = MEASUREMENTMODEL(X,V,M,K,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jul-2015 13:22:57

h = v;
