function f = processExplicitODE(x,v,m,k,omega,Amplitude,t)
%PROCESSEXPLICITODE
%    F = PROCESSEXPLICITODE(X,V,M,K,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jul-2015 13:22:56

f = [v;-(k.*x-Amplitude.*sin(omega.*t))./m];
