function f = processExplicitODENonLinear(x,v,m,k1,k2,omega,Amplitude,t)
%PROCESSEXPLICITODENONLINEAR
%    F = PROCESSEXPLICITODENONLINEAR(X,V,M,K1,K2,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    20-Jul-2015 13:12:15

f = [v;-(k1.*x-Amplitude.*sin(omega.*t)+k2.*x.^2.*sign(x))./m];
