function h_jointState = measurementModelJointState(x,v,F,m,k1,k2,c)
%MEASUREMENTMODELJOINTSTATE
%    H_JOINTSTATE = MEASUREMENTMODELJOINTSTATE(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Jul-2015 02:36:31

h_jointState = [v;F];
