function f_jointState = processExplicitODEJointState(x,v,F,m,k1,k2,c)
%PROCESSEXPLICITODEJOINTSTATE
%    F_JOINTSTATE = PROCESSEXPLICITODEJOINTSTATE(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Jul-2015 02:36:32

t2 = x.^2;
f_jointState = [v;-(-F+c.*v+k1.*x+k2.*t2.*x)./m;0.0;0.0;0.0;0.0];
