function df_jointState = dynamicsDerivativesJointState(x,v,F,m,k1,k2,c)
%DYNAMICSDERIVATIVESJOINTSTATE
%    DF_JOINTSTATE = DYNAMICSDERIVATIVESJOINTSTATE(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Jul-2015 02:36:32

t2 = 1.0./m;
t3 = x.^2;
df_jointState = reshape([0.0,-t2.*(k1+k2.*t3.*3.0),0.0,0.0,0.0,0.0,1.0,-c.*t2,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,-t2.*x,0.0,1.0,0.0,0.0,0.0,-t2.*t3.*x,0.0,0.0,1.0,0.0,0.0,-t2.*v,0.0,0.0,0.0,1.0],[6, 6]);
