function dh_jointState = outputsDerivativesJointState(x,v,F,m,k1,k2,c)
%OUTPUTSDERIVATIVESJOINTSTATE
%    DH_JOINTSTATE = OUTPUTSDERIVATIVESJOINTSTATE(X,V,F,M,K1,K2,C)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Jul-2015 02:36:33

dh_jointState = reshape([0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2, 6]);
