function df_dX = dynamicsDerivativesNonLinear(x,v,m,k1,k2,omega,Amplitude,t)
%DYNAMICSDERIVATIVESNONLINEAR
%    DF_DX = DYNAMICSDERIVATIVESNONLINEAR(X,V,M,K1,K2,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jul-2015 14:27:14

df_dX = reshape([0.0,-(k1+k2.*x.*sign(x).*2.0+k2.*x.^2.*dirac(x).*2.0)./m,1.0,0.0],[2, 2]);
