function df_dX = dynamicsDerivatives(x,v,m,k,omega,Amplitude,t)
%DYNAMICSDERIVATIVES
%    DF_DX = DYNAMICSDERIVATIVES(X,V,M,K,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jul-2015 13:22:54

df_dX = reshape([0.0,-k./m,1.0,0.0],[2, 2]);
