function dh_dX = outputsDerivatives(x,v,m,k,omega,Amplitude,t)
%OUTPUTSDERIVATIVES
%    DH_DX = OUTPUTSDERIVATIVES(X,V,M,K,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    15-Jul-2015 15:05:54

dh_dX = [0.0,1.0];
