function dh_dX = outputsDerivativesNonLinear(x,v,m,k1,k2,omega,Amplitude,t)
%OUTPUTSDERIVATIVESNONLINEAR
%    DH_DX = OUTPUTSDERIVATIVESNONLINEAR(X,V,M,K1,K2,OMEGA,AMPLITUDE,T)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jul-2015 14:27:16

dh_dX = [0.0,1.0];
